[theme]
primaryColor = "#B10967"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#412761"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
